### ISSUE TITLE
About singler.rmd , any human reference specifized tissue, like liver

### ISSUE THREAD

**Issue by star9926** [mousepixels/sanbomics_scripts#1]
Dear Sanbomics,

Thanks a lot for your efforts, that did inspire me a lot, 
while I have an issue that is there any solution for human reference specifized for various tissues, exactly like what "TabulaMurisData" did in mus musculus. 
Thanks again.

Best regards,
Na

**Comment by star9926** [comment]
Dear Snabomics,

I found [Tabula Muris Consortium], who developed TabulaMurisData, recently have reported similar data for human, https://pubmed.ncbi.nlm.nih.gov/35549404/ , but still no open data available in R. Hopeful soon for automatically usage.
Maybe it will take some time for usage.
Best regards,
Na

**Comment by mousepixels** [comment]
Hi, sorry for the late response. I see you found tabula sapiens, which is what I would have recommended. You can convert the adata to an R object then do label transfer.
