### ISSUE TITLE
single-cell RNA velocity analysis

### ISSUE THREAD

**Issue by dfmontielg** [mousepixels/sanbomics_scripts#2]
Hi,

I really appreciate your tutorial on scRNA velocity.

I am trying to merge my output loom file from velocyto and my preprocessed counts like you did here:
        adata = pp('../tutorial_sample/outs/filtered_feature_bc_matrix/')
        ldata = scv.read('../tutorial_sample/velocyto/tutorial_sample.loom')
        adata = scv.utils.merge(adata, ldata)

My question is does the dimensions of the two objects should match exactly? Or when you do the merge it will look for the intersect barcodes/cells and the intersection of genes? In my case it does the merge but the spliced and unspliced information does not appear in the new object and I guess because the dimensions does not match. 

Thank you,
Diego

**Comment by mousepixels** [comment]
Hi, sorry for the late response. Were you able to figure this out?
