### ISSUE TITLE
high_quality_volcano_plots.ipynb

### ISSUE THREAD

**Issue by victorsanchezarevalo** [mousepixels/sanbomics_scripts#4]
Hi Mark,

Thank you very much for the code it is really useful. 

I am just a beginer...I was thinking in a volcano plot in which dowregulated genes are in blue and over expressed genes in red leaving the non differentailly expressed genes in grrey. Could you give me any advise, please? .

Thanks a lot

Vic

**Comment by victorsanchezarevalo** [comment]
I am trying with this funcion but it does not work:

def map_color(a):
    log2FoldChange, nlog10 = a
    
    if abs(log2FoldChange) < 1 or nlog10 < 2:
        return 'no significant'
    elif abs(log2FoldChange) > 1.5 and nlog10 > 2:
        return 'upregulated'
    elif abs(log2FoldChange) < -1.5 and nlog10 > 2:
        return 'downregulated'
    
    return

df['color'] = df[['log2FoldChange', 'nlog10']].apply(map_color, axis = 1)

**Comment by mousepixels** [comment]
Hi. abs() is the absolute value. So for the up/down genes you need to remove it. Should be something like this:

```
if abs(log2FoldChange) < 1 or nlog10 < 2:
    return 'no significant'
elif log2FoldChange > 1.5 and nlog10 > 2:
    return 'upregulated'
elif log2FoldChange < -1.5 and nlog10 > 2:
    return 'downregulated'
```

or:

```
if log2FoldChange > 1.5 and nlog10 > 2:
    return 'upregulated'
elif log2FoldChange < -1.5 and nlog10 > 2:
    return 'downregulated'
return 'not significant'
```

**Comment by victorsanchezarevalo** [comment]
Thanks a lot!

I really appreciate your help.

Best

Vic

**Comment by mousepixels** [comment]
No problem!
