### ISSUE TITLE
reproducing from filtered matrix

### ISSUE THREAD

**Issue by giorgiatosoni** [mousepixels/sanbomics_scripts#5]
Hi, 

Thank you so much for your walkthrough video!

I'm trying to reproduce your analysis on my samples. Instead of .cvs files, I have the filtered_feature_bc_matrix output of cellranger.
How could I reproduce your integration code to preprocess all the samples at once? Creating a folder containing the filtered_feature_bc_matrix of every sample and itereting through them, or converting adata to .cvs? I tried both but I'm stuck..

Thanks!

**Comment by giorgiatosoni** [comment]
solved by transforming in h5ad :)

**Comment by mousepixels** [comment]
Hi! Sorry just saw this, glad you got it working.
