### ISSUE TITLE
use better `pip install` approach in tutorials

### ISSUE THREAD

**Issue by fomightez** [mousepixels/sanbomics_scripts#7]
I ran across your [tutorial here](https://github.com/mousepixels/sanbomics_scripts/blob/main/single_cell_analysis_complete_class.ipynb) as part of looking into [this Biostars post](https://www.biostars.org/p/9540763/#9540763).

I don't know where you suggest people run this code; however, if it is in standard Jupyter, I'd suggest you update your examples of `pip install` to not include use of the exclamation point. For example, in that [Jupyter notebook I referenced](https://github.com/mousepixels/sanbomics_scripts/blob/main/single_cell_analysis_complete_class.ipynb) the fifth cell has an example. I would suggest you change it to `%pip install scvi-tools`. In the last few years the magic command `%pip install` (and related `%conda install`) were added to insure that when running `pip install` in Jupyter notebooks, the installation occurs in the environment that backs the notebook kernel. This is something the use of the exclamation point alone with `pip install` failed to do and caused all sorts of issues. You can read more about the modern `%pip install` and `%conda install` magic commands [here](https://discourse.jupyter.org/t/why-users-can-install-modules-from-pip-but-not-from-conda/10722/4?u=fomightez).

Unfortunately, I think Google Colab derived their offshoot of the Jupyter interface before that happened, and so it isn't consistent. I'm not 100% sure about the Google Colab notebooks and what is best; however, for standard Jupyter use of the magic command is best. And so if you direct people using your stuff to Google Colab mostly, I can understand using the outdated syntax.

It's also good to be aware that because modern Jupyter installations most often have automagics enabled by default, `pip install` without any symbol will use the modern magic command behind the scenes, and so even no symbol is better than suggesting the exclamation point with `pip install` now. However, explicit is best for learners and future you.

**Comment by mousepixels** [comment]
Thanks for the comment. You are right, I should start using %. I think I was just always used to using ! and actually never had an issue until just recently where I actually had to use %.
