### ISSUE TITLE
Integration question + consulting work?

### ISSUE THREAD

**Issue by smitapath** [mousepixels/sanbomics_scripts#8]
Hi Mark,

I'm running your scripts on my local computer and it crashed when I tried to integrate the 26 samples- I got an out of memory error. Question- if I didn't integrate, could I look at each sample alone and get the same data out- or does integration do something to the data (ie normalize with respect to each other?) so I would want to integrate everything?

Second question, my single cell data is interesting- we do depletion using CRISPR-cas9 to remove abundant, ribo, and mito targets. This redistributes reads onto low expression targets. Would you modify anything in the workflow in that scenario? Are you available for hire as a consultant?

Thanks,
Smita

**Comment by mousepixels** [comment]
Hi! Which script/integration are you trying? How much memory do you have? 

This depends on the data and what question you are trying to ask. If you are making a comparison in each sample that is independent of other samples, then this would probably be fine. But if you are trying to compare across samples or conditions you should integrate because it does correct for batch, etc.

Huh, that does sound like an interesting dataset. I'm not sure because I don't know what script/workflow the issue is in reference to. Likely the changes would be minimal if anything, but I would need to know a little more about experiment/model/targets. Ummm.. let me DM you about the final point.

**Comment by smitapath** [comment]
Hi Mark,
I'm running your tutorial using the examples in the Nature paper that you point to. So those 26 samples that you use- it got about halfway through and then crashed. I checked the memory and it's 16GB but only 4GB is available. 

I'm completely new to single cell data analysis and am finding your tutorial to be the most thorough and comprehensive available currently (already ran through the R and Seurat version). My customer data is not in the .csv raw counts format that you started with and when I start with the read_10x_mtx , I suspect my dataframe is different because when I do MT removal using your commands, my plot has different values in the cells and the violin plot doesn't show anything for MT and ribo. I'm not currently savy enough to modify your commands to work with the matrix file dataframe.

If you are available to hire as a consultant, we are very interested- I have permission and funding to get a GitHub site built to help our customers work with their data for secondary analysis.

Thanks for the work that you do- it's so helpful,
Smita

**Comment by mousepixels** [comment]
Are these mouse data? The problem with the MT/ribo quantification is the capitalization of genes for mouse and human are different. And the matching is case sensitive. Usually human are capitalized and mouse are lowercase except for the first letter.

16 gb is enough memory for a small dataset with only a few samples. But I would suggest investing in a computer with at least 64 gb of ram if you plan do do these kind of analysis frequently. RAM is required but the other things (e.g., number of cpu) usually just benefit speed. So you can make a pretty budget friendly computer with 64 gb ram that works.

If you leave your email I can talk to you about the latter point.

**Comment by smitapath** [comment]
No it's human. I can show you the output being different when I blindly follow your commands with different input files.  But the first column that is returned in the mito filtration section is different (you have gene name and I have UMI) or something like that.

I ordered 64gb and it's coming tomorrow - thank you for that input.
