### ISSUE TITLE
showing selected genenames on the plot

### ISSUE THREAD

**Issue by mars188** [mousepixels/sanbomics_scripts#9]
Hello,

I have created a volcano plot with your method and it looks good. I am just stuck on one step.  

I created a list of selected 5 genes as below: 
`pikced10 = ('gene1', 'gene2', 'gene3', 'gene4', 'gene5') `

Now, I want to show names of these selected 5 genes on the plot. I know you have shown
`if df.iloc[i].nlog10 > 5 and abs(df.iloc[i].log2FoldChange) > 2:` 

but I am confused how can I show my customized list. 

How can I feed this info/list of gene into the script so when I plot the graph the names of only these 5 genes are shown?

Many thanks,

**Comment by mousepixels** [comment]
You can replace the if statement with an if statement like: `if x in picked10:` and x being the same thing you set s to from the dataframe

**Comment by mars188** [comment]
Thank you for your response. I tried the following script:

texts = []
for i in range(len(df)):
    if i in picked10:
        texts.append(plt.text(x = df.iloc[i].log2FoldChange, y = df.iloc[i].nlog10, s = df.iloc[i].symbol,
                              fontsize = 12, weight = 'bold'))

it does produce the image but does not label the gene names in picked10 list. 

Please check the script and help me in fixing this. Many thanks!

**Comment by mars188** [comment]
Here is the full script that I obtained from your tutorial and trying to run with my own data to get volcano plot. 


plt.figure(figsize = (6,6))

ax = sns.scatterplot(data = df, x = 'log2FoldChange', y = 'nlog10', 
                     hue = 'color', hue_order = ['Not_significant', 'Significant', 'tumor_suppressor'],
                     palette = ['grey', 'orangered', 'darkblue'])                     
                    
                     
texts = []
for i in range(len(df)):
if i in picked10:
        texts.append(plt.text(x = df.iloc[i].log2FoldChange, y = df.iloc[i].nlog10, s = df.iloc[i].symbol,
                              fontsize = 12, weight = 'bold'))
        
plt.legend(loc = 1, bbox_to_anchor = (1.4,0.95), frameon = False, prop = {'weight':'bold'})

ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

ax.tick_params(width = 1)

plt.xlabel("$log_{2}$ fold change", size = 15)
plt.ylabel("-$log_{10}$ FDR", size = 15)

plt.savefig('volcano.png', dpi = 1200, bbox_inches = 'tight', facecolor = 'white')
plt.show()

**Comment by mars188** [comment]
As I mentioned above, it does produce a nice volcano plot but just doesn't label the genes I provided in "picked10" list. 

Sorry I am new to python so can't figure this out by my own. 

Many thanks for your time and help.

**Comment by mars188** [comment]
![volcano_python](https://user-images.githubusercontent.com/59919950/197963989-08c68989-2d6d-4b25-abdd-dcbfed6dc658.png)

Here is the exact code the I executed. My purpose is to label (show names) of the genes called "marker"

**Comment by mars188** [comment]
Basically, "picked2" list contains all the genes I called "marker"

**Comment by mars188** [comment]
![volcano](https://user-images.githubusercontent.com/59919950/197970730-a4d39480-52c7-427d-bad8-32e28dcf3d65.png)

Here, I have attached the figure that the above script generates... I want to label "marker" in "green" with gene names. 

Please let me know what should I label the gene names. Many thanks and sorry for several messages.

**Comment by mousepixels** [comment]
Hi, sorry for the late reply. You added the texts to list but you never added them to the plot. You need to add:

`adjust_text(texts, arrowprops = dict(arrowstyle = '-', color = 'k'))`

You can also try my graphing package I made recently, in the future:

`%pip install sanbomics`
`from sambomics.plots import plots`
`volcano(....)`

**Comment by mousepixels** [comment]
I'm going to go ahead and close this. Let me know if you have any further issues

**Comment by mars188** [comment]
Dear @mousepixels 

Thank you so much for your response. I have added the script that you mentioned but it still does not label the gene names. Please see attached my script.
![volcano_python](https://user-images.githubusercontent.com/59919950/198202008-3b981f85-8f48-4cd2-8c53-34c6b444844f.png)

I need your help in 2 things. 

1. please check the script and suggest any changes that will allow labelling the genes in the picked2 list.

2. Circles indicating "tumor_suppressor" genes are sent in the background (as you can see in the figure above) but I want to bring them to the front with "zorder" option I guess? Please write a script for that. 

I am sorry for so many questions but I am new to python. Your this tutorial can generate the volcano plot that I am looking for. 

Many thanks in advance.

**Comment by mousepixels** [comment]
It's your `for i in (df)` line. All that is doing is looping over the columns of df. You need to loop over the rows of the df. Look at how I do it in my notebook.

You can do this potentially two ways. 1) plot them as a separate axis on top or 2) change the order of the dataframe to include them on the top or the bottom (try both, im not sure which order it plots in). Im not sure if #2 will work or not but it will be easier.

**Comment by mars188** [comment]
Dear @mousepixels 

Thank you for your response. I have corrected the script according to your notebook but it still doesn't label the gene names. when I select `if df.iloc[i].nlog10 > 5 and abs(df.iloc[i].log2FoldChange) > 2:` option, as you did, then it works fine and labels the gene names. However, when I replace this with `if i in picked2:` it does generate the figure but does not label the gene names. Could it be `if i in picked2:` that is causing it to not label? How can I correct it? 

I have attached a screenshot of the whole script, please take a look and suggest any edits. 

Many thanks for your time. 

Best regards, 
![Untitled](https://user-images.githubusercontent.com/59919950/198996017-e8aee079-9fa0-41db-9cb2-bddb6f3d24d8.png)
